sudo: required
services:
  - docker

before_install:
  - docker build -t youjian/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t youjian/multi-client ./client
  - docker build -t youjian/multi-nginx ./nginx
  - docker build -t youjian/multi-server ./server
  - docker build -t youjian/multi-worker ./worker
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push youjian/multi-client
  - docker push youjian/multi-nginx
  - docker push youjian/multi-server
  - docker push youjian/multi-worker

