sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aiscream/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true aiscream/react-test npm test

after_success:
  - docker build -t aiscream/multi-client ./client
  - docker build -t aiscream/multi-nginx ./nginx
  - docker build -t aiscream/multi-server ./server
  - docker build -t aiscream/multi-worker ./worker
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aiscream/multi-client
  - docker push aiscream/multi-nginx
  - docker push aiscream/multi-server
  - docker push aiscream/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker2"
  env: "Multidocker2-env"
  bucket_name: "elasticbeanstalk-eu-west-2-443710600322"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY